server:
    port: 8089
boy:
    height: 170
    weight: 80
spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/boy?useSSL=false
      username: root
      password: password
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
    